const { Player } = require('../models');

const playerData = [
    {
        character_name: 'Dragon',
        player_race: 'Dragonborn',
        player_class: 'Paladin',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 1

    },
    {
        character_name: 'Draco',
        player_race: 'Dragonborn',
        player_class: 'Paladin',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 2
    },
    {
        character_name: 'Leroy Jenkins',
        player_race: 'Elf',
        player_class: 'Fighter',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 3
    },
    {
        character_name: 'Dwight',
        player_race: 'Gnome',
        player_class: 'Cleric',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 2
    },
    {
        character_name: 'Ted',
        player_race: 'Elf',
        player_class: 'Druid',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 3
    },
    {
        character_name: 'Larry',
        player_race: 'Human',
        player_class: 'Ranger',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 1
    },
    {
        character_name: 'Merlin',
        player_race: 'Half-Elf',
        player_class: 'Warlock',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 1
    },
    {
        character_name: 'Chester',
        player_race: 'Dwarf',
        player_class: 'Monk',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 2
    },
    {
        character_name: 'Slick',
        player_race: 'Bard',
        player_class: 'Rogue',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 3
    },
    //
    {
        character_name: 'Dragonaria',
        player_race: 'Dragonborn',
        player_class: 'Paladin',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 4

    },
    {
        character_name: 'Dra',
        player_race: 'Dragonborn',
        player_class: 'Paladin',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 4
    },
    {
        character_name: 'Leroy Menkins',
        player_race: 'Elf',
        player_class: 'Fighter',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 6
    },
    {
        character_name: 'Dwightingale',
        player_race: 'Gnome',
        player_class: 'Cleric',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 6
    },
    {
        character_name: 'Rasputin',
        player_race: 'Elf',
        player_class: 'Druid',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 5
    },
    {
        character_name: 'Belph',
        player_race: 'Human',
        player_class: 'Ranger',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 7
    },
    {
        character_name: 'Meliodis',
        player_race: 'Half-Elf',
        player_class: 'Warlock',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 8
    },
    {
        character_name: 'Leafoy',
        player_race: 'Dwarf',
        player_class: 'Monk',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 9
    },
    {
        character_name: 'Wit',
        player_race: 'Bard',
        player_class: 'Rogue',
        level: 1,
        armor_class: 1,
        health: 1,
        strength: 1,
        dexterity: 1,
        constitution: 1,
        wisdom: 1,
        intelligence: 1,
        charisma: 1,
        pp: 1,
        party_id: 10
    } 
]

const seedPlayers = () => Player.bulkCreate(playerData);

module.exports = seedPlayers;